---
  - name: install essential software
    sudo: yes
    apt: name={{ item }} state=present
    with_items:
      - git
      - vim
      - python
      - python-pip   

  - name: install ansible
    sudo: yes
    shell: pip install ansible
 
  - name: set variable
    set_fact: repo="ansible-tower" 
 
  - name: copy
    synchronize: src=~/{{ repo }} dest=~/
  
  - name: install tower
    sudo: yes
    shell: cd /home/{{ deploy_user }}/{{ repo }} && ./configure -o tower_setup_conf.yml 
 
  - name: install tower setup
    sudo: yes
    shell: cd /home/{{ deploy_user }}/{{ repo }} && ./setup.sh
